apiVersion: apps/v1
kind: Deployment
metadata:
  name: medium-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: medium-app
  template:
    metadata:
      labels:
        app: medium-app
    spec:
      containers:
      - name: frontend
        image: frontend:latest
      - name: backend
        image: backend:latest